version: "2"
services:
  mongo:
    image: mongo:3.2.8
    restart: always
    ports:
      - "27017"
  crater:
    image: jedwards1211/crater
    ports:
      - "3000:80"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/crater
      - 'METEOR_SETTINGS={"public": {"test": "success"}}'
    depends_on:
      - mongo
